language: c
script: ./scripts/travis-build.sh
env:
    - PROJECT=magenta-pc-x86-64
    - PROJECT=magenta-qemu-arm64
    - PROJECT=magenta-qemu-arm32

sudo: false

cache:
    directories:
    - prebuilt/downloads

notifications:
    irc:
        channels:
            - "chat.freenode.net#fuchsia-dev"
        skip_join: true
        use_notice: true
